"""FIRM-4B v2.3.1 natural-prompt calibration curriculum.

The v2.3 post-quantization audit showed that long answers were learned mostly when
prompts explicitly requested a "complete" or "technical" answer.  This module
reweights ordinary user wording, critical fact correction, short-thinking/long-final
examples, and multi-turn expansion behavior.
"""
from firm4b_v2_3_depth import DEPTH_CASES, SOURCES, word_count

CRITICAL_PROMPTS = {
"to_header_materials": [
 "Which metals are common in hermetic TO headers?",
 "What metal would you expect in a detector TO header?",
 "Are hermetic TO headers usually steel or Kovar?",
 "What are transistor-outline headers normally made from?",
 "For an IR detector package, what is the TO header material?",
 "Why do some TO headers use Kovar while others use steel?",
 "What structural alloys are used for glass-sealed TO headers?",
 "What would a package drawing mean by a Kovar TO header?",
 "Is Kovar a normal material for a detector header?",
 "What metal systems are typical around TO glass feedthroughs?",
 "How do I tell whether a TO header is Kovar or cold-rolled steel?",
 "What are the usual bulk metals under the plating on a TO header?",
 "For a hermetic optical TO package, what header alloys should I expect?",
 "What material choice controls the glass-to-metal seal in a TO header?",
 "Are TO headers one standard alloy or does the seal design determine it?",
 "What should I assume about TO-header metallurgy if the drawing is missing?",
],
"to66_construction": [
 "What is an optoelectronic TO-66 package physically made from?",
 "Describe a hermetic TO-66 detector package.",
 "Is a detector-style TO-66 a metal package or a molded plastic package?",
 "How is a TO-66 optical detector package constructed?",
 "What are the main parts of a hermetic TO-66 header and cap?",
 "What does a metal TO-66 package look like internally?",
 "How are the feedthrough pins insulated in a TO-66 detector header?",
 "For a laser or detector, how is a TO-66 header usually built?",
 "Does TO-66 specify plastic, or can it be a metal-glass package?",
 "What would I expect in a hermetic TO-66 assembly?",
 "How does an optoelectronic TO-66 differ from a molded power package?",
 "What is the base, pin seal, and cap construction of a TO-66 detector package?",
 "Why are some TO-66 detector packages clearly plated metal?",
 "What package construction is typical for a cooled detector in a TO-66 outline?",
 "How would a thermoelectric cooler be mounted inside a TO-66 detector package?",
 "What does the TO-66 outline tell me about construction and what does it not tell me?",
],
"krs5_identity": [
 "What material is KRS-5?",
 "What is the composition of the IR crystal KRS-5?",
 "Tell me about KRS-5 infrared windows.",
 "Is KRS-5 a semiconductor or an optical crystal?",
 "What is KRS-5 used for in FTIR optics?",
 "Why would an infrared spectrometer use KRS-5?",
 "What is thallium bromoiodide used for in infrared optics?",
 "What does the trade name KRS-5 refer to?",
 "What wavelengths make KRS-5 useful as an IR window?",
 "What are the main advantages and drawbacks of KRS-5?",
 "Is KRS-5 a thallium-halide material?",
 "Why does KRS-5 require special handling?",
 "What should I know before using a KRS-5 window?",
 "How is KRS-5 different from a detector semiconductor?",
 "What kind of crystal is sold as KRS-5?",
 "What makes KRS-5 useful despite its toxicity and softness?",
 "What is the chemical material behind KRS-5 optical components?",
 "What is KRS5 in an infrared optics catalog?",
 "Is KRS-5 related to TlBr and TlI?",
 "Why is KRS-5 associated with very broad IR transmission?",
],
"mct_direct_gap": [
 "Does HgCdTe have a direct bandgap?",
 "What kind of bandgap does MCT have?",
 "Is MCT direct-gap or indirect-gap?",
 "Why is HgCdTe strongly absorbing near its IR band edge?",
 "Does photon absorption in HgCdTe need a phonon?",
 "How does the band structure of MCT help infrared detection?",
 "What is the optical consequence of HgCdTe being direct-gap?",
 "Why can HgCdTe use relatively thin absorbing layers?",
 "Is the tunable gap in HgCdTe a direct gap?",
 "Correct the claim that MCT is an indirect-gap semiconductor.",
 "What should I remember about HgCdTe momentum-space band extrema?",
 "Why does direct-gap absorption matter for MCT photodiodes?",
 "Does changing Cd fraction make HgCdTe indirect-gap?",
 "How are direct gap and composition tunability related in HgCdTe?",
 "What bandgap fact is essential when comparing MCT with InSb?",
 "Why is calling MCT indirect-gap physically misleading?",
],
"mct_vs_insb_overview": [
 "How do HgCdTe and InSb compare as infrared detector materials?",
 "MCT or InSb: what are the important detector tradeoffs?",
 "What are the practical differences between an HgCdTe detector and an InSb detector?",
 "When would you choose MCT instead of InSb?",
 "When would InSb be preferable to HgCdTe?",
 "Compare HgCdTe with InSb for a cooled infrared imager.",
 "How do MCT and InSb differ beyond being II-VI versus III-V?",
 "What matters when deciding between HgCdTe and InSb?",
 "Compare the spectral range, cooling, transport, and fabrication of HgCdTe and InSb.",
 "Which is more spectrally tunable, HgCdTe or InSb?",
 "How do HgCdTe and InSb compare for MWIR work?",
 "Can InSb replace HgCdTe for LWIR detection?",
 "What advantages does InSb have over MCT and what does MCT have over InSb?",
 "Compare the detector physics and manufacturing burden of HgCdTe and InSb.",
 "If both are cooled, how do InSb and MCT differ in practical performance?",
 "Why is HgCdTe used across more IR bands than InSb?",
 "What would an IR detector engineer compare before selecting MCT or InSb?",
 "Give me the engineering differences between InSb and HgCdTe.",
],
"mct_vs_insb_photonics": [
 "How do HgCdTe and InSb compare optically?",
 "Compare the photonic properties of HgCdTe and InSb.",
 "How are the absorption edges of MCT and InSb different?",
 "Do MCT and InSb both have direct bandgaps?",
 "How does spectral tunability differ between InSb and HgCdTe?",
 "Compare the IR absorption physics of InSb and MCT.",
 "What is different about the cutoff wavelength of MCT versus InSb?",
 "Which optical properties matter when comparing InSb with HgCdTe?",
 "Why can MCT cover LWIR while InSb is mainly an MWIR material?",
 "How does composition affect MCT optical response compared with InSb?",
 "Compare absorption, bandgap and cutoff in MCT and InSb.",
 "What does the fixed InSb gap mean compared with alloy-tuned HgCdTe?",
 "How would you describe the photon-coupling differences between MCT and InSb?",
 "What is the practical optical consequence of MCT alloy composition?",
 "How do temperature and bandgap affect the spectra of InSb and HgCdTe?",
 "Which material gives more freedom to engineer the detector band edge, InSb or MCT?",
],
}

GENERIC_NATURAL_WRAPPERS = [
 "{q}",
 "Can you explain {ql}",
 "I am working on an infrared detector. {q}",
 "For detector engineering, {q}",
 "In practical IR work, {q}",
 "{q0}",
 "I need to understand this for a device design: {q}",
 "How should I think about this in the lab: {ql}",
 "For a detector design review: {q}",
 "From a semiconductor-device perspective, {q}",
 "What should I know about this: {ql}",
 "In an IR-device context, {q}",
]

REASON_HINTS = {
"to_header_materials":"Separate package outline from metallurgy; distinguish compression-seal steel from matched-seal Kovar/Alloy 52, then keep plating separate from bulk metal.",
"to66_construction":"Treat optoelectronic TO-66 as a hermetic metal/glass assembly; cover header, feedthrough seals, die/TEC platform, cap and window.",
"kovar_role":"Explain CTE matching to sealing glass, oxide bonding and hermetic thermal-cycle reliability; contrast with copper-like heat spreading.",
"matched_vs_compression":"Contrast matched CTE design with deliberate compressive loading after cooldown; associate Kovar/Alloy 52 versus cold-rolled steel appropriately.",
"to_plating":"Separate structural alloy from surface finish; explain corrosion, soldering, wire bonding and welding functions of Ni/Au.",
"krs5_identity":"Protect the identity: KRS-5 is TlBr-TlI thallium bromoiodide, a broad-band IR optical crystal, not a Ge-As detector semiconductor.",
"krs5_compare":"Compare bandwidth, refractive/mechanical properties and handling; KRS-5 trades extreme IR range for softness/toxicity.",
"mct_direct_gap":"Protect the direct-gap fact and connect it to strong near-edge absorption and composition-tunable cutoff.",
"mct_vs_insb_overview":"Compare direct-gap physics, tunable versus fixed gap, spectral coverage, transport, cooling, growth/process burden and use-case selection.",
"mct_vs_insb_photonics":"Both are direct-gap; focus on tunable HgCdTe absorption edge versus fixed InSb gap, plus absorption and temperature implications.",
"mct_vs_insb_transport":"Compare very high InSb electron mobility with composition-dependent HgCdTe transport and thermal-generation limits set by gap/cutoff.",
"mct_vs_insb_growth":"Contrast binary InSb growth with composition-sensitive ternary HgCdTe plus Hg vapor/surface/substrate constraints.",
"mct_cutoff":"State the bandgap model and temperature; convert cutoff to Eg, then solve Eg(x,T), emphasizing model/cutoff convention.",
"insb_identity":"Define binary III-V, narrow direct gap and high mobility, then connect narrow gap to thermal generation and cooling.",
"cdznte_role":"Explain lattice matching and defect reduction, then manufacturing penalties and alternative-substrate buffer strategies.",
"ingaas_depth":"Near In0.53Ga0.47As is InP lattice matched; extended InGaAs changes composition and incurs mismatch/dark-current penalties.",
"mct_vs_t2sl":"Compare tunable direct bulk HgCdTe with engineered III-V type-II superlattice bands, interfaces, absorption, lifetime and manufacturing ecosystems.",
"die_attach_complete":"Prioritize thermal resistance, bond line, CTE stress, modulus, cure, electrical isolation, contamination and qualification—not one catalog metric.",
"wet_etch_complete":"Name bromine families, then compare isotropy, mask/sidewall chemistry, stoichiometry, passivation and electrical leakage/noise.",
"hg_loss_complete":"Frame Hg control as local chemical potential/partial pressure; include reservoir, thermal gradients, free volume, dwell and verification.",
"passivation_noise_complete":"Separate DC leakage/surface stability from fluctuating interface charge; diagnose with bias, frequency, temperature, geometry and controls.",
"noise_metrics_complete":"Keep spectral density, integrated RMS noise, NEP, detectivity and D* definitions/units distinct and connect them mathematically.",
"gr_vs_1f_complete":"Contrast Lorentzian lifetime-related G-R noise with approximate 1/f excess noise; use bias, temperature, geometry and corner behavior.",
"hall_device_complete":"Hall probes bulk/sheet transport while two-terminal measurements include contacts, surfaces, junctions and parallel paths.",
}

MULTITURN_CASES = [
("to_kovar_followup",
 "What metals are used in hermetic detector headers?",
 "Steel and controlled-expansion alloys such as Kovar are both common, depending on the glass-to-metal seal design.",
 "Could it specifically be Kovar?",
 "to_header_materials"),
("to_material_followup",
 "I have a plated metal TO detector package.",
 "That is normal for a hermetic optoelectronic package; the visible finish does not necessarily reveal the bulk header alloy.",
 "What is the header underneath the plating likely to be?",
 "to_header_materials"),
("krs_correction_followup",
 "KRS-5 is some kind of infrared material, right?",
 "Yes. It is used as an infrared optical material.",
 "What is it actually made of and why is it useful?",
 "krs5_identity"),
("krs_semiconductor_followup",
 "Is KRS-5 a detector semiconductor?",
 "No. Its usual role is as an infrared-transmitting optical crystal rather than an active detector semiconductor.",
 "Then explain what material it is and its main optical tradeoffs.",
 "krs5_identity"),
("mct_insb_expand",
 "HgCdTe is II-VI and InSb is III-V.",
 "Correct, but that taxonomy alone does not determine which one is the better detector material.",
 "What are the practical differences that actually matter?",
 "mct_vs_insb_overview"),
("mct_insb_more",
 "Give me a quick comparison of HgCdTe and InSb.",
 "Both are direct-gap infrared semiconductors; HgCdTe has a composition-tunable gap while InSb is a fixed-composition binary material.",
 "Go deeper. How would I actually choose between them?",
 "mct_vs_insb_overview"),
("mct_insb_optical_followup",
 "Both InSb and MCT absorb infrared photons.",
 "Yes. Both are direct-gap photon-detector materials.",
 "How do their optical properties and cutoffs compare?",
 "mct_vs_insb_photonics"),
("mct_gap_correction",
 "I heard MCT has an indirect gap.",
 "That premise is incorrect for detector-relevant HgCdTe.",
 "Explain the correct bandgap physics and why it matters.",
 "mct_direct_gap"),
("die_attach_followup",
 "I want the highest thermal-conductivity epoxy for an HgCdTe die.",
 "Thermal conductivity matters, but it is not sufficient to choose a reliable die attach.",
 "What else should control the choice?",
 "die_attach_complete"),
("etch_followup",
 "I found an HgCdTe etchant that gives a smooth-looking mesa.",
 "Visual smoothness is useful, but it does not prove the sidewall is electronically benign.",
 "What should I compare before adopting the etch?",
 "wet_etch_complete"),
("hg_seal_followup",
 "My HgCdTe LPE ampoule is sealed, so mercury loss should be solved.",
 "Sealing limits gross loss, but it does not guarantee the intended local Hg chemical potential at the growth solution.",
 "What actually controls the local Hg condition?",
 "hg_loss_complete"),
("noise_followup",
 "Passivation reduced DC leakage on my detector.",
 "That is encouraging, but it does not guarantee lower low-frequency noise.",
 "How could the 1/f noise still get worse and how would I test it?",
 "passivation_noise_complete"),
("ingaas_followup",
 "InGaAs is lattice matched to InP.",
 "That is only true near the standard In0.53Ga0.47As composition.",
 "What changes for extended-InGaAs?",
 "ingaas_depth"),
("cdznte_followup",
 "CdZnTe is a good HgCdTe substrate because it is lattice matched.",
 "Yes, lattice matching is a major reason it can support low-defect HgCdTe epitaxy.",
 "Why would anyone use a different substrate then?",
 "cdznte_role"),
]

def generic_variants(q):
    q0=q.rstrip("?.")
    ql=q0[:1].lower()+q0[1:]
    return [w.format(q=q,ql=ql,q0=q0) for w in GENERIC_NATURAL_WRAPPERS]
